apiVersion: v1
kind: Secret
metadata:
  name: chproxy-config
  namespace: statist
type: Opaque
stringData:
  config.yml: |
    ---
    hack_me_please: true

    caches:
      - name: "shortterm"
        mode: "redis"
        redis:
          addresses:
            - "rc1b-ougvwpvuac47ryik.mdb.yandexcloud.net:6379"
          username: "default"
          password: $REDIS_PASSWORD
        expire: "1h"
        shared_with_all_users: true

    network_groups: []
    param_groups: []

    server:
      http:
        listen_addr: ":8080"

    users:
      - name: $CLICKHOUSE_USER_TEST
        password: $CLICKHOUSE_PASSWORD_TEST
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_USER_TEST
        cache: "shortterm"

      - name: $CLICKHOUSE_PROJECT_OWNER_USER_DEV
        password: $CLICKHOUSE_PROJECT_OWNER_PASSWORD_DEV
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_PROJECT_OWNER_USER_DEV
        cache: "shortterm"

        max_concurrent_queries: 10
        max_execution_time: 10s
        requests_per_minute: 30
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

      - name: $CLICKHOUSE_DWH_USER
        password: $CLICKHOUSE_DWH_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_DWH_USER
      
        max_concurrent_queries: 10
        max_execution_time: 10s
        requests_per_minute: 30
        cache: "shortterm"
        
        # The maximum number of requests that may wait for their chance
        # to be executed because they cannot run now due to the current limits.
        #
        # This option may be useful for handling request bursts from `tabix`
        # or `clickhouse-grafana`.
        #
        # By default all the requests are immediately executed without
        # waiting in the queue.
        max_queue_size: 10

        # The maximum duration the queued requests may wait for their chance
        # to be executed.
        # This option makes sense only if max_queue_size is set.
        # By default requests wait for up to 10 seconds in the queue.
        max_queue_time: 10s

      - name: $CLICKHOUSE_SME_USER
        password: $CLICKHOUSE_SME_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_SME_USER

        max_concurrent_queries: 5
        max_execution_time: 10s
        requests_per_minute: 15
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

      - name: $CLICKHOUSE_CHARTS_USER
        password: $CLICKHOUSE_CHARTS_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_CHARTS_USER

        max_concurrent_queries: 30
        max_execution_time: 60s
        requests_per_minute: 30
        max_queue_time: 10s
        max_queue_size: 20
        cache: "shortterm"

      - name: $CLICKHOUSE_DCO_USER
        password: $CLICKHOUSE_DCO_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_DCO_USER

        max_concurrent_queries: 5
        max_execution_time: 10s
        requests_per_minute: 15
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

      - name: $CLICKHOUSE_VOIP_TEAM_USER
        password: $CLICKHOUSE_VOIP_TEAM_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_VOIP_TEAM_USER

        max_concurrent_queries: 5
        max_execution_time: 10s
        requests_per_minute: 15
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

      - name: $CLICKHOUSE_REDALERT_USER
        password: $CLICKHOUSE_REDALERT_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_REDALERT_USER

        max_concurrent_queries: 5
        max_execution_time: 10s
        requests_per_minute: 15
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

      - name: $CLICKHOUSE_MB_ANALYTICS_USER
        password: $CLICKHOUSE_MB_ANALYTICS_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_MB_ANALYTICS_USER

        max_concurrent_queries: 5
        max_execution_time: 10s
        requests_per_minute: 15
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"
    
      - name: $CLICKHOUSE_ANALYTICS_SERVICE_USER
        password: $CLICKHOUSE_ANALYTICS_SERVICE_PASSWORD
        to_cluster: "yandex_cloud"
        to_user: $CLICKHOUSE_ANALYTICS_SERVICE_USER

        max_concurrent_queries: 8
        max_execution_time: 30s
        requests_per_minute: 30
        max_queue_time: 10s
        max_queue_size: 10
        cache: "shortterm"

    clusters:
      - name: "yandex_cloud"
        scheme: "http"
        nodes: $CLICKHOUSE_NODES
        kill_query_user:
          name: $CLICKHOUSE_USER_TEST
          password: $CLICKHOUSE_PASSWORD_TEST
        users:
          - name: $CLICKHOUSE_USER_TEST
            password: $CLICKHOUSE_PASSWORD_TEST
          - name: $CLICKHOUSE_PROJECT_OWNER_USER_DEV
            password: $CLICKHOUSE_PROJECT_OWNER_PASSWORD_DEV
          - name: $CLICKHOUSE_DWH_USER
            password: $CLICKHOUSE_DWH_PASSWORD
          - name: $CLICKHOUSE_CHARTS_USER
            password: $CLICKHOUSE_CHARTS_PASSWORD
          - name: $CLICKHOUSE_SME_USER
            password: $CLICKHOUSE_SME_PASSWORD
          - name: $CLICKHOUSE_DCO_USER
            password: $CLICKHOUSE_DCO_PASSWORD
          - name: $CLICKHOUSE_VOIP_TEAM_USER
            password: $CLICKHOUSE_VOIP_TEAM_PASSWORD
          - name: $CLICKHOUSE_REDALERT_USER
            password: $CLICKHOUSE_REDALERT_PASSWORD
          - name: $CLICKHOUSE_MB_ANALYTICS_USER
            password: $CLICKHOUSE_MB_ANALYTICS_PASSWORD
          - name: $CLICKHOUSE_ANALYTICS_SERVICE_USER
            password: $CLICKHOUSE_ANALYTICS_SERVICE_PASSWORD
